# backend:
  # name: git-gateway
  # repo: Irene-IT/ireneM  # commit
  # branch: main
  # publish_mode: editorial_workflow 

  # Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Irene-IT/ireneM
  branch: main
  identity_url: https://auth.decapbridge.com/sites/da1c70a0-93c0-4c63-ae9c-6327d07f4d34
  gateway_url: https://gateway.decapbridge.com

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/content/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/content/work.md"
        label: "Work Page"
        name: "work"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Portfolio Items", name: "items", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Link", name: "link", widget: "string" }
            ] }

      - file: "src/content/faq.md"
        label: "FAQ Page"
        name: "faq"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Questions", name: "questions", widget: "list", fields: [
              { label: "Question", name: "q", widget: "string" },
              { label: "Answer", name: "a", widget: "text" }
            ] }

      - file: "src/content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "LinkedIn", name: "linkedin", widget: "string" }


# ++++++++++++++++++++++++++++++++++
# Use DecapBridge auth (required)
# backend:
#   name: git-gateway
#   repo: Irene-IT/ireneM
#   branch: main
#   identity_url: https://auth.decapbridge.com/sites/da1c70a0-93c0-4c63-ae9c-6327d07f4d34
#   gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
   commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://irenemyronova.netlify.app